# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YumFun' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YumFun
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'TensorFlowLiteSwift/CoreML', '~> 2.4.0'

  # Firestore integration
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'

  # Cloud Storage integration
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage' 		
  
  pod 'TensorFlowLiteSwift/CoreML', '~> 2.4.0'
 
  # Activity Indicator
  pod 'NVActivityIndicatorView'

  # Alert View
  pod 'JSSAlertView'

  # Image Cropper
  pod 'QCropper'

  # Image Compressor 
  pod 'WXImageCompress', '~> 0.1.1'

  # Progress HUD
  pod 'JGProgressHUD'
  
  # Notification and Alert
  pod 'SwiftEntryKit', '1.2.7'

  # Multi-tier UIScrollView
  pod 'SegementSlide', '3.0.1'
  # App Store Card View
  pod 'Cards'
  
  # Animated Text Field
  pod 'AnimatedField'

  # Comet BG animated
  pod "Comets"

  # Gradient Color
  pod "Pastel"

  # Helper Color Utility
  pod 'Hue'

  # Button Lib
  pod "LGButton"

  # View Transition Lib
  pod 'Hero'

  # Email Validator
  pod 'EmailValidator'

  # Programmatical Autolayout
  pod 'SnapKit', '~> 5.0.0'

  # Icon Lib
  pod 'SwiftIconFont'

  # Recipe searching and parsing		
  pod 'Alamofire', '~> 5.2'
  pod 'Kanna', '~> 5.2.2'

  # Floating Button
  pod 'JJFloatingActionButton'
 
  # Easier Layout for Collection View
  pod 'Blueprints'
end
